apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: atcdemo-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: atcdemo
  template:  
    metadata: # Dictionary
      name: atcdemo-pod
      labels: # Dictionary
        app: atcdemo  # Key value pairs
    spec:
      containers: # List
        - name: atcdemo-container
          image: public.ecr.aws/q1x1f8q8/demotask:1     
          ports: 
            - containerPort: 80  
    